# Generated by Django 6.0.3 on 2026-06-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_allocation_allocated_at_allocation_distance_km_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooddonation",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="food_photos/"),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("donor", "Donor"), ("ngo", "NGO"), ("admin", "Admin")],
                default="donor",
                max_length=10,
            ),
        ),
    ]
